upgrade pngquant

diff --git a/deps/pngquant/configure b/deps/pngquant/configure
--- a/deps/pngquant/configure
+++ b/deps/pngquant/configure
@@ -3,29 +3,19 @@
 CONFIG="config.mk"
 PREFIX="/usr/local"
 
-test -f lib/libimagequant.h || { git submodule init && git submodule update; } || {
-    echo "error: libimagequant not found in ./lib/"
-    echo "If you're using git, do clone with --recursive, or download from https://github.com/ImageOptim/libimagequant"
-    exit 1;
-}
-VERSION=$(grep LIQ_VERSION_STRING lib/libimagequant.h | grep -Eo "2\.[0-9.]+")
-
 DEBUG=
+LIQSRCDIR=./lib
+LIQCONFIGURE=(--quiet)
 SSE=auto
 OPENMP=
 LIBPNG_DIR=.
-if [[ "$OSTYPE" =~ "darwin" ]]; then
-    COCOA_READER=auto
-    LCMS2=0
-else
-    COCOA_READER=0
-    LCMS2=auto
-fi
+LCMS2=auto
 EXTRA_CFLAGS=
 EXTRA_LDFLAGS=
 
 # make gcc default compiler unless CC is already set
 CC=${CC:-gcc}
+SKIP_CC_CHECK=0
 
 help() {
     printf "%4s %s\n" "" "$1"
@@ -33,7 +23,7 @@ help() {
 
 for i in "$@"; do
     case $i in
-    --help)
+    --help|-h)
         echo
         help "--prefix=<dir>                installation directory [$PREFIX]"
         help "--extra-cflags=<flags>        append to CFLAGS"
@@ -42,6 +32,7 @@ for i in "$@"; do
         help "--enable-debug"
         help "--enable-sse/--disable-sse    enable/disable SSE instructions"
         echo
+        help "--with-libimagequant=<dir>    external libimagequant (lib/ default)"
         help "--with-openmp=static          compile with multicore support"
         help "--with-lcms2/--without-lcms2  compile with color profile support"
 if [[ "$OSTYPE" =~ "darwin" ]]; then
@@ -58,54 +49,70 @@ fi
     # Can be set before or after configure. Latter overrides former.
     CC=*)
         CC=${i#*=}
+        SKIP_CC_CHECK=1
+        LIQCONFIGURE+=("$i")
         ;;
     CFLAGS=*)
         CFLAGS=${i#*=}
+        LIQCONFIGURE+=("$i")
         ;;
     LDFLAGS=*)
         LDFLAGS=${i#*=}
+        LIQCONFIGURE+=("$i")
         ;;
     --enable-debug)
         DEBUG=1
+        LIQCONFIGURE+=("$i")
         ;;
     --enable-sse)
         SSE=1
+        LIQCONFIGURE+=("$i")
         ;;
     --disable-sse)
         SSE=0
+        LIQCONFIGURE+=("$i")
         ;;
     --with-openmp)
         OPENMP=1
+        LIQCONFIGURE+=("$i")
         ;;
     --with-openmp=static)
         OPENMP=static
+        LIQCONFIGURE+=("$i")
         ;;
     --with-lcms2)
         LCMS2=1
-        COCOA_READER=0
         ;;
     --without-lcms2)
         LCMS2=0
         ;;
     --with-cocoa)
-        COCOA_READER=1
-        LCMS2=0
+        LCMS2=auto
         ;;
     --without-cocoa)
-        COCOA_READER=0
+        LCMS2=auto
         ;;
     --with-libpng=*)
         LIBPNG_DIR=${i#*=}
         ;;
+    --with-libimagequant=*)
+        LIQSRCDIR=${i#*=}
+        ;;
+    --with-libimagequant)
+        LIQSRCDIR=""
+        ;;
     --prefix=*)
         PREFIX=${i#*=}
+        LIQCONFIGURE+=("$i")
         ;;
     # can be used multiple times or in quotes to set multiple flags
     --extra-cflags=*)
         EXTRA_CFLAGS="$EXTRA_CFLAGS ${i#*=}"
+        LIQCONFIGURE+=("$i")
         ;;
     --extra-ldflags=*)
         EXTRA_LDFLAGS="$EXTRA_LDFLAGS ${i#*=}"
+        LIQCONFIGURE+=("$i")
         ;;
     *)
         echo "warning: unknown switch ${i%%=*} (see $0 --help for the list)"
@@ -155,7 +162,8 @@ find_pkgconfig() {
     if pkg-config --exists "$LIBNAME" &> /dev/null; then
         cflags "$(pkg-config --cflags "$LIBNAME")"
         lflags "$(pkg-config --libs "$LIBNAME")"
-        status "$LIBNAME" "shared ($(pkg-config --modversion "$LIBNAME"))"
+        LIBRARY_FOUND_VERSION=$(pkg-config --modversion "$LIBNAME")
+        status "$LIBNAME" "shared ($LIBRARY_FOUND_VERSION)"
         return 0
     fi
     return 1
@@ -170,9 +178,10 @@ find_static() {
     if [ -n "$HPATH" ]; then
         local APATH=$(find_f . "$STATICPATTERN")
         if [ -n "$APATH" ]; then
+            LIBRARY_FOUND_HEADER=$HPATH
             cflags "-I${HPATH%/*}"
             lflags "${APATH}"
-            status "$LIBNAME" "static"
+            status "$LIBNAME" "static ($APATH)"
             return 0
         fi
     fi
@@ -190,6 +199,7 @@ find_dynamic() {
     if [ -n "$HPATH" ]; then
         local SOPATH=$(find_f "$LIBDIR" "$DYNAMICPATTERN")
         if [ -n "$SOPATH" ]; then
+            LIBRARY_FOUND_HEADER=$HPATH
             cflags "-I${HPATH%/*}"
             lflags "-L${SOPATH%/*} -l$DYNAMICLIBNAME"
             status "$LIBNAME" "shared ... $SOPATH"
@@ -205,6 +215,20 @@ find_library() {
     local HEADERPATTERN=$3
     local STATICPATTERN=$4
     local DYNAMICPATTERN=$5
+
+    # other functions will overwrite it
+    LIBRARY_FOUND_HEADER=
+    LIBRARY_FOUND_VERSION=
+    LIBRARY_FOUND_BUILD=
+
+    if [ "imagequant" = "$LIBNAME" -a -n "$LIQSRCDIR" -a -f "$LIQSRCDIR"/"$HEADERPATTERN" ]; then
+        status "$LIBNAME" "build static"
+        cflags "-I$LIQSRCDIR"
+        lflags "$LIQSRCDIR/libimagequant.a"
+        LIBRARY_FOUND_HEADER="$LIQSRCDIR"/"$HEADERPATTERN"
+        LIBRARY_FOUND_BUILD="$LIQSRCDIR"
+        return 0;
+    fi
 
     # try static in current directory first
     if find_static "$LIBNAME" "$HEADERPATTERN" "$STATICPATTERN"; then
@@ -247,9 +271,15 @@ error() {
 echo
 
 # /tmp, because mingw has problems opening /dev/null and gives false negative
-# if ! echo "int main(){}" | "$CC" -xc -std=c99 -o /tmp/gcccheck - > /dev/null; then
-#     error "Compiler" "$CC failed to compile anything (make sure it's installed and supports C99)"
-# fi
+#if ! echo "int main(){}" | "$CC" -xc -std=c99 -o pngquant-gcccheck - > /dev/null; then
+#    rm -f pngquant-gcccheck
+#    if [ "$SKIP_CC_CHECK" -eq 1 ]; then
+#        status "Compiler" "$CC failed to compile anything (make sure it's installed and supports C99)"
+#    else
+#        error "Compiler" "$CC failed to compile anything (make sure it's installed and supports C99)"
+#    fi
+#fi
+rm -f pngquant-gcccheck
 
 status "Compiler" "$CC"
 
@@ -315,17 +345,8 @@ fi
 
 # Cocoa
 if [[ "$OSTYPE" =~ "darwin" ]]; then
-    cflags "-mmacosx-version-min=10.6"
-    lflags "-mmacosx-version-min=10.6"
-
-    if [ "$COCOA_READER" != 0 ] && "$CC" 2>/dev/null 1>/dev/null -xc -E <(echo "#import <Cocoa/Cocoa.h>"); then
-        COCOA_READER=1
-        cflags "-DUSE_COCOA=1"
-        lflags "-framework Cocoa"
-        status "Cocoa" "yes"
-    else
-        status "Cocoa" "no"
-    fi
+    cflags "-mmacosx-version-min=10.7"
+    lflags "-mmacosx-version-min=10.7"
 fi
 
 # pairs of possible *.h and lib*.so locations
@@ -335,7 +356,13 @@ if command -v >/dev/null libpng-config; then
     DIRS+=("$(libpng-config --prefix) $(libpng-config --libdir)")
 fi
 
-DIRS+=("/usr/local/include /usr/local/lib"
+if [ -n $"LIQSRCDIR" ]; then
+    DIRS+=("$LIQSRCDIR" "$LIQSRCDIR") # local libimagequant
+fi
+
+DIRS+=(
+      "/usr/local/include /usr/local/lib"
+      "/usr/include /usr/lib64"
       "/usr/include /usr/lib"
       "/opt/local/include /opt/local/lib" # macports
       )
@@ -354,6 +381,34 @@ else
     SOLIBSUFFIX=so
 fi
 
+
+# libimagequant
+if [ "./lib" = "$LIQSRCDIR" -a -d ".git" -a ! -f "lib/Cargo.toml" ]; then
+    git submodule init && git submodule update;
+fi
+
+
+if find_library "imagequant" "imagequant" "libimagequant.h" "libimagequant.a" "libimagequant.$SOLIBSUFFIX*"; then
+    if [ -n "$LIBRARY_FOUND_VERSION" ]; then
+        VERSION=$LIBRARY_FOUND_VERSION
+    elif [ -n "$LIBRARY_FOUND_HEADER" ]; then
+        VERSION=$(grep LIQ_VERSION_STRING "$LIBRARY_FOUND_HEADER" | grep -Eo "2\.[0-9.]+")
+    else
+        VERSION=unknown
+    fi
+
+    if [ -n "$LIBRARY_FOUND_BUILD" ]; then
+        STATICLIBDEPS="$LIBRARY_FOUND_BUILD/libimagequant.h $LIBRARY_FOUND_BUILD/libimagequant.a"
+        LIQSRCDIR="$LIBRARY_FOUND_BUILD"
+    fi
+else
+    if [ -n "$LIQSRCDIR" -a ! -f "$LIQSRCDIR"/libimagequant.h ]; then
+        echo "If you're using git, do clone with --recursive, or download from https://github.com/ImageOptim/libimagequant"
+        error "imagequant" "libimagequant.h not found in $LIQSRCDIR/"
+    else
+        error "imagequant" "not found. Get it from https://github.com/ImageOptim/libimagequant and build it in ./lib/"
+    fi
+fi
 
 # libpng
 # try if given flags are enough
@@ -476,9 +531,9 @@ VERSION = $VERSION
 CC = $CC
 CFLAGS = $CFLAGS
 LDFLAGS = $LDFLAGS
-COCOA_READER = $COCOA_READER
 SOLIBSUFFIX = $SOLIBSUFFIX
+STATICLIBDEPS = $STATICLIBDEPS
+LIQSRCDIR = $LIQSRCDIR
+LIQCONFIGUREFLAGS = $(printf "'%s' " "${LIQCONFIGURE[@]}")
 " > "$CONFIG"
 
-# Configure static library the same way
-cp "$CONFIG" lib/
